---

- name: OP the Minecraft user
  become: yes
  become_user: minecraft    
  command:
    chdir: /opt/minecraft/ 
    cmd: /usr/bin/tmux send-keys -t mcs '/op {{ minecraft_user }}' ENTER     
  ignore_errors: yes
  when: minecraft_user != ""

- name: Whitelist the Minecraft user
  become: yes
  become_user: minecraft        
  command:
    chdir: /opt/minecraft/ 
    cmd: /usr/bin/tmux send-keys -t mcs '/whitelist add {{ minecraft_user }}' ENTER
  ignore_errors: yes
  when: minecraft_user != ""

- name: Run Chunky Pregenerator to pre-generate 5000 blocks
  become: yes
  become_user: minecraft        
  command:
    chdir: /opt/minecraft/ 
    cmd: /usr/bin/tmux send-keys -t mcs '/chunky radius 5000' ENTER '/chunky start' ENTER